services:
  wewe-auth:
    build: auth
    ports:
      - "9001:9001"
    depends_on:
      - redis

  wewe-resource:
    build: resource
    depends_on:
      - wewe-auth

  wewe-client:
    build: client
    depends_on:
      - wewe-auth
      - wewe-resource
    ports:
      - "8080:8080"
    environment:
      # TODO: вынести в docker secrets
      CLIENT_SECRET: "{noop}secret"

  redis:
    image: redis
    restart: always
    ports:
      - "6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local