spring:
  application.name: client
  security:
    oauth2:
      client:
        registration:
          # Client Credentials Flow
          wewe-client-client-credentials:
            provider: spring
            client-id: wewe-client
            client-secret: "{noop}secret"
            authorization-grant-type: client_credentials
            scope:
              - openid
              - profile
              - read
            client-name: wewe-client-client-credentials

          # Authorization Code Flow
#         wewe-authorization-code:
#           provider: sprting
#           client-id: wewe-client
#           client-secret: "secret"
#           authorization-grant-type: authorization_code
#           redirect-uri: "http://wewe-client:8080/authorized"
#           scope: message.read,message.write
#           client-name: wewe-client-authorization-code
        provider:
          spring:
            issuer-uri: http://wewe-auth:9001

resourceServer.baseUri: http://wewe-resource:9002/secrets

logging:
  level:
    # Уровень логирования для Spring Boot
    org.springframework.boot: TRACE
    # Уровень логирования для всего Spring Security
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.server.resource: TRACE
    org.springframework.security.web: TRACE
    org.springframework.security.authentication: TRACE
    # Уровень логирования для Spring Cloud Gateway (если используется)
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE
    reactor.netty.http.server: TRACE
    # Уровень логирования для веб-запросов (если используется RestTemplate или WebClient)
    org.springframework.web.client.RestTemplate: TRACE
    org.springframework.web.reactive.function.client: TRACE
    org.springframework.web: TRACE
    # Уровень логирования для HTTP-запросов (используя сторонний Logbook)
    org.zalando.logbook: TRACE
    org.apache.http: TRACE
    org.apache.http.wire: TRACE

logbook:
  filter.enabled: false
  secure-filter.enabled: false
  format.style: http
  minimum-status: 200
